#! /bin/sh

# kill any processes that might be lingering on the port
if ! [ -z "$(lsof -t -i :8000)" ]; then
    echo "Killing process at port 8000..."
    kill $(lsof -t -i :8000)
else
    echo "No process needed to be interrupted."
fi

# remove existing static files
rm -rf /static/*

# compile the source code into the distribution repository
./manage.py collectstatic

# minify resulting css files
oenv/bin/css-html-js-minify static/css/

# minify resulting javascript files
oenv/bin/css-html-js-minify static/js/app.js
oenv/bin/css-html-js-minify static/js/utils.js

# start running server.js, mute the output, and run in the background
echo "App is now running on port 3000!"
uwsgi --http :8000 --module omu.wsgi > /dev/null&
