#! /bin/sh

# kill any processes that might be lingering on the port
if ! [ -z "$(lsof -t -i :8000)"  ]; then
    echo "Killing process at port 8000..."
    kill $(lsof -t -i :8000)
else
    echo "No process needed to be interrupted."
fi

uwsgi --http :8000 --module omu.wsgi --chmod-socket=664 > /dev/null&1
