#! /bin/sh

# kill any processes that might be lingering on the port
if ! [ -z "$(lsof -t -i :3001)"  ]; then
    echo "Killing process at port 3001..."
    kill $(lsof -t -i :3001)
else
    echo "No process needed to be interrupted."
fi

uwsgi --http :3001 --module omu.wsgi --chmod-socket=664 > /dev/null&1
