# Generated by Django 2.1.7 on 2019-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omuthecat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicklog',
            name='number_of_clicks',
        ),
        migrations.AddField(
            model_name='clicklog',
            name='clicker_id',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
