# Generated by Django 2.1.7 on 2019-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omuthecat', '0002_auto_20190315_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopClickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicker_id', models.CharField(default='null', max_length=512)),
                ('clicks', models.PositiveSmallIntegerField(default=0)),
                ('datetime_logged', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'desktop_clicks',
            },
        ),
        migrations.RenameModel(
            old_name='ClickLog',
            new_name='MobileClickLog',
        ),
        migrations.AlterModelTable(
            name='mobileclicklog',
            table='mobile_clicks',
        ),
    ]
