# Generated by Django 2.1.7 on 2019-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omuthecat', '0003_auto_20190315_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='null', max_length=128, null=True)),
                ('message', models.TextField(max_length=512)),
                ('datetime_logged', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'guestbook_logs',
            },
        ),
    ]
