# Generated by Django 2.1.7 on 2019-03-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omuthecat', '0004_guestbooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='null', max_length=128, null=True)),
                ('message', models.TextField(max_length=512)),
                ('clicker_id', models.CharField(max_length=512)),
                ('clicks', models.PositiveSmallIntegerField(default=0)),
                ('datetime_logged', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'guestbook',
            },
        ),
        migrations.DeleteModel(
            name='GuestbookLog',
        ),
    ]
